### ISSUE TITLE
Implement multiple hand bets

### ISSUE THREAD

**Issue by rbrants** [Agadar/DankTimesBot-Plugin-Blackjack#13]
Like when you split a hand. You can play 2 (or even more) hands if you bet multiple times in the same game. 
Right now the problem with split and multi-hand is the player limit of 3. If you shuffle in multiple decks like a real casino does (which will increase casino win rate unfortunately), you have more cards to play with and you can increase player limit to like 8 per table with the option to split (multiple times).

**Comment by rbrants** [comment]
Maybe also add the option to do things like /bjbet 1234 2 (bet 1234 for 2 hands)

**Comment by Agadar** [comment]
For splitting, see issue https://github.com/Agadar/DankTimesBot-Plugin-Blackjack/issues/10.

Multiple hands betting is certainly a possibility. As suggested, might be good to increase number of decks and available player slots to compensate.

**Comment by Agadar** [comment]
Update: player limit was removed. Number of decks used for a game is now equal to number of players.

**Comment by Agadar** [comment]
Implemented in latest commit. Decided not to add second parameter because it should not be too easy to run like 10 hands simultaneously with just one command.
