### ISSUE TITLE
Implement other ways to bet

### ISSUE THREAD

**Issue by rbrants** [Agadar/DankTimesBot-Plugin-Blackjack#14]
Like all (all-in).
Maybe add:
- /bjbet half (half of your total points)
- /bjbet 💯 and other emoji's
- /bjbet double (previous bet x2)
- /bjbet @Agadar's money
- etc

**Comment by Agadar** [comment]
I see merit for /bjbet half and /bjbet double, but emojis and someone else's specific amount of points is not something I've ever seen someone (wanting to) use, so won't be adding those.

**Comment by Agadar** [comment]
Implemented /bjbet half indirectly as core bot now supports it. /bjbet double is to come later.

**Comment by Agadar** [comment]
Implemented /bjbet previous and /bjbet double. This should satisfy the request.
